# Generated by Django 3.1.1 on 2020-09-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_en', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_en', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_en', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('description_en', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ordering', models.IntegerField()),
                ('image', models.FileField(upload_to='static/images')),
                ('icon', models.FileField(upload_to='static/icons')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beotura.category')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beotura.tour')),
            ],
        ),
    ]
