# Generated by Django 3.1.1 on 2020-12-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beotura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Place', to='beotura.category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Place', to='beotura.tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
